### ISSUE TITLE
How to build an executable for a glimmer-dsl-libui app

### ISSUE THREAD

**Issue by AndyObtiva** [alx3dev/executable-ruby#1]
Hi,

I just tried this gem on the Mac with this `exer` script run from within the [glimmer-dsl-libui](https://github.com/AndyObtiva/glimmer-dsl-libui) project directory:

```ruby
Exer.make do |app|
  app.filename = './examples/basic_window.rb'
  app.add :binary_exist, 'git'
  app.add :gem_install, 'glimmer-dsl-libui'
end
```

When I executed the `exer exer_config.rb` command, it produced `.app` and `.exe` files.

When I ran the `.app` file, it detected Ruby correctly and installed `glimmer-dsl-libui`.

```
% exer exer_config.rb 
3.0.2 :001 > Exer.make do |app|
3.0.2 :002 >       app.filename = './examples/basic_window.rb'
3.0.2 :003?>     app.add :binary_exist, 'git'
3.0.2 :004?>     app.add :gem_install, 'glimmer-dsl-libui'
3.0.2 :005?>   end
 => 1 
3.0.2 :006 > 

% examples/basic_window.rb.app 
[+] Found ruby binary: /Users/andymaleh/.rvm/rubies/ruby-3.0.2/bin/ruby
[+] Ruby Version: 3.0.2
[+] Ruby Platform: x86_64-darwin19
[+] Found git binary: /usr/bin/git
[+] Found gem binary: /Users/andymaleh/.rvm/rubies/ruby-3.0.2/bin/gem
Successfully installed glimmer-dsl-libui-0.5.4
1 gem installed


Press [ENTER] key to exit
```

However, it did not launch the `./examples/basic_window.rb` app. 

Did I do something wrong?

**Comment by alx3dev** [comment]
Filename is used to generate executables, there is no option to open any file (yet, just because I wanted to make sure it works). I am working on documentation at the moment, and methods to start file, but I want it be easily extendible to run any script and/or command,  so we could also use `git clone` and direct download if there is no git command. To see how it works, delete line 39 in `lib/exer/make.rb` (`File.delete`). Few words about process:

`add_function` add function to the go file
`add` add function to `main` in go file, to be actually executed

```ruby
Exer.make do |x|
  x.filename = 'name' => this is name of go file and executables
  x.add_function :gem_install => add function gem_install to golang file (this is added by default)
  x.add :gem_install, 'glimmer-dsl-libui' => this will add command in main function (actually execute)
  x.add :ruby_exec, 'some function' => this will run function with ruby -e
  x.add :binary_exist, 'git' => this will check for git 
```
Now I am adding more methods to do what we actually want, together with detail documentation (how and why).

**Comment by alx3dev** [comment]
I just updated answer with how it will look like.... so this is bump comment :)
